### ISSUE TITLE
Torrent downloads for recorded talks

### ISSUE THREAD

**Issue by CodingSpiderFox** [voc/streaming-website#226]
I am curious why there are no torrent downloads for the recorded talks on media.ccc.de

Wouldn't the CCC save quite a lot of data transfer costs and also offer potentially better bandwith options if the media files were distributed as bittorrent downloads?

**Comment by lukas2511** [comment]
We offered torrent downloads in the past but that resulted in various issues: Technical (no peers and torrent clients ignoring http upstreams), privacy concerning (p2p revealing IPs) as well as from a management perspective (depublishing talks on request by the speakers or even re-uploaded talks with fixes for video/audio). It was decided to fully remove torrent support from our platform. Since our servers are sponsored we also have no issues with cost and we have plenty of bandwidth available over our various mirrors (both our own as well as externally provided ones).
