### ISSUE TITLE
Add current time display to event schedule under streams

### ISSUE THREAD

**Issue by mk-fg** [voc/streaming-website#87]
Hi, 

As the subject line suggests, it would be nice to have a current time display on events at links like https://streaming.media.ccc.de/35c3/halla , as otherwise times stated on such pages have no relation to anything.

I.e. coming from non-EU timezone, you can't tell in which timezone they are specified, how long it is until any of the times there and such.

To illustrate, imagine you're in Tahiti, time is XX:YY, and (without looking it up) see whole page of e.g. https://streaming.media.ccc.de/35c3/halla , as it is attached below.
You can clearly see timestamps on events there, but can you tell anything useful from them, e.g. in how long you should check back on a stream to start, or when specific even will be in your time?

I think putting current timestamp in the same exact format and timezone as events there under "now" (point marked "A" in the image) label will solve this issue - e.g. it'd read something like "now: 10:08 CET" (at point marked "A") and next event is clearly marked as "11:00 - 11:30" (point marked "B"), so about 50 minutes until that.

Cheers!

![screen shot 2018-12-27 at 13 56 55-fullpage](https://user-images.githubusercontent.com/227121/50473778-2899c080-09e0-11e9-9f58-88bf1ffb83ca.png)

**Comment by dedeibel** [comment]
Good idea

**Comment by jidanni** [comment]
Yes, being that it is using a strange timezone, it would be good to know what "now" is.
![32064-0](https://user-images.githubusercontent.com/1230959/86514285-0e963500-be44-11ea-8778-6cfdaf59461c.jpg)

**Comment by iSchluff** [comment]
So I took a look at the code and it seems like all times from the schedule are converted to unix timestamps (so the timezone info of the original event is lost) and then passed to strftime in the html template so all times like %H:%M in the page are currently in CET/CEST, because that is what the server uses.

The position of the now marker is determined locally by the browser by comparing unix timestamps. So the good news is that the position of the marker may be correct most of the time, but I don't yet see what the best strategy is for converting the times.

There's also some things wrong with the current setup: If the event is not happening in CET/CEST and the viewer is also outside that timezone the times don't make any sense at all. Also the now marker might be completely off if the viewer hasn't properly configured their system clock.

Off the top of my head two variants seem reasonable going forward:

1. Always using the events local timezone (So preserving the timezone info contained in the schedule.xml if it exists). That means the now marker would need to also show time in that timezone (and find out about summer time and stuff ...).
2. Always using your local browser time+timezone. However this requires that the viewer has a properly configured system.

I guess 1. maybe makes a little more sense as times mentioned during a stream would probably be in that timezone.

**Comment by jidanni** [comment]
Well maybe give the user some choices, including "GMT", and save it in a cookie.
Also e.g., CST means both Taipei time and Chicago time, so be sure to also show "+08:00" etc.

**Comment by iSchluff** [comment]
I think adding more options than Local and Event time is overkill because listing all the timezones is a bit strange.

Assuming the user even knows what his timezone/offset is.

**Comment by jidanni** [comment]
E.g., https://2020.stateofthemap.org/programme/#general_Saturday
Some schedules come in UTC. So the user might want to make the times on the player match the schedule.
And who knows what other schedules the user might want to match. So I would add flexibility.

**Comment by iSchluff** [comment]
I think adding more options than Local and Event time is overkill because listing all the timezones is a bit strange.

Assuming the user even knows what his timezone/offset is.
